language: ruby

rvm: 2.3.5
sudo: false
matrix:
  include:
    - rvm: 2.3.5
    - rvm: 2.4.2
    - rvm: 2.5.0
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

os:
  - linux

addons:
  apt:
    packages:
      - protobuf

before_install:
  - gem install bundler

script:
  - gem list -l
  - bundle exec rake
  - bundle exec codeclimate-test-reporter
  - gem build ./iowa.gemspec

bundler_args: --jobs 1 --retry 3

notifications:
  email: false
