version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: iowa
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8901:8080

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
